version: '3'
services:
  borgmatic:
    image: b3vis/borgmatic@sha256:8fbc8a3f82de1da24a40cb74f5624b6b2455f7f1e36982a4cf3c6a8996a1d258
    container_name: borgmatic
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro           # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository     # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/ # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg  # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                  # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg    # checksums used for deduplication
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
